Repository sematic-ai/helm-charts, pull requests merged in 2023-04, with the labels that each got.

#19 Release v0.28.0
  index.yaml
  sematic-server/sematic-server-1.1.6.tgz
Labels: release

#20 Release v0.28.1
  index.yaml
  sematic-server/sematic-server-1.1.7.tgz
Labels: release

#22 Add sematic-grafana-dashboards v1.0.0
  index.yaml
  sematic-grafana-dashboards/sematic-grafana-dashboards-1.0.0.tgz
Labels: enhancement

#24 Add sematic-grafana-dashboards v1.0.0 with parameterized urls
  index.yaml
  sematic-grafana-dashboards/sematic-grafana-dashboards-1.0.0.tgz
Labels: enhancement

#26 Add docs for cron config
  README.md
Labels: documentation
